spring:
  application:
    name: Trabajo Practico Tenpo Microservicio
  server:
    port: 8085
  profiles:
    active: ${APP_PROFILE:dev}
    group:
      prod:
        - application-pgsql
      dev:
        - application-h2

    include:
      - kafka

feign:
  client:
    config:
      connectTimeout: 5000
      readTimeout: 5000
    default-to-properties: true

FeignApi:
  url: https://www.random.org
  numero: 2
  decimal: 1
  col: 1
  formato: plain

logging:
  level:
    com.IPorcentajeService: DEBUG
    root: INFO
    com.challengeTenpo: DEBUG
    # Con las siguientes lineas se crea una carpeta y un archivo de logs en la raiz del proyecto
#  file:
#    name: logs/application.log

# URL para acceder a Swagger: http://localhost:8085/swagger-ui.html