spring:
  application:
    name: Trabajo Practico Tenpo Microservicio
  server:
    port: 8085
  profiles:
    active: ${APP_PROFILE:dev}
    group:
      prod: pgsql,kafka
      dev: h2, kafka-mock
      local-kafka: h2, kafka
  jpa:
    open-in-view: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

FeignApi:
  url: https://www.random.org
  numero: 2
  decimal: 1
  col: 1
  formato: plain

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      springframework: WARN
      hibernate: WARN
    com.challengeTenpo: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# http://localhost:8085/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs
