spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/challenge_db
    username: challenge_user
    password: challenge_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true